services:
  database:
    container_name: 'postgres-dev-assistech'
    image: 'postgres:16.0-alpine3.18'
    env_file:
      - .env.development
    environment:
      POSTGRES_PASSWORD: 'local_password'
    ports:
      - '5432:5432'
